In [5]:
import pandas as pd
from sklearn import model_selection

data_path =  r'C:\GN\Projects\Datasets\AAAMLP_datasets/'
output_path = r'C:\GN\Projects\Datasets\AAAMLP_outputs/'

In [6]:
if __name__ == "__main__":
    df=pd.read_csv(data_path+"adult.csv")

    df['kfold'] = -1

    # Shuffle
    df = df.sample(frac=1).reset_index(drop=True)

    ## Initiate k_fold
    kf = model_selection.KFold(n_splits=5)

    for fold,(trn_,val_) in enumerate(kf.split(X=df)):
        df.loc[val_,'kfold'] = fold

    # fill the new kfold col
    # fold keeps track of sets created by kf.split(). fold is from enumerate
    # trn_,val_ keeps track of indexes in the respective kf.split() set
    # Thus using val_ index in each set we can specify folds for entire df
    # Refer below examples for more clarity

    df.to_csv(output_path+"adult_folds.csv",index = False)

In [17]:
>>> import numpy as np
>>> from sklearn.model_selection import KFold
>>> X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
>>> y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=4)
kf.get_n_splits(X)

>>> for fold,(train_index, test_index) in enumerate(kf.split(X)):
...     print("Fold:",fold,"TRAIN:", train_index, "TEST:", test_index)
...     X_train, X_test = X[train_index], X[test_index]
...     y_train, y_test = y[train_index], y[test_index]

Fold: 0 TRAIN: [1 2 3] TEST: [0]
Fold: 1 TRAIN: [0 2 3] TEST: [1]
Fold: 2 TRAIN: [0 1 3] TEST: [2]
Fold: 3 TRAIN: [0 1 2] TEST: [3]


In [28]:
for i in kf.split(X):
    print(i)

(array([1, 2, 3]), array([0]))
(array([0, 2, 3]), array([1]))
(array([0, 1, 3]), array([2]))
(array([0, 1, 2]), array([3]))


In [26]:
for i in enumerate(range(100,120,2)):
    print(i)

(0, 100)
(1, 102)
(2, 104)
(3, 106)
(4, 108)
(5, 110)
(6, 112)
(7, 114)
(8, 116)
(9, 118)
